options:
  channel:
    type: string
    default: stable
    description: |
      Snap channel to install wsgate from.
  region:
    type: string
    default: RegionOne
    description: |
      Keystone region
  wsgate-port:
    type: int
    default: 8080
    description: |
      WSGate listen port
  vip:
    type: string
    default: !!null ""
    description: |
      Virtual IP(s) to use to front API services in HA configuration.

      If multiple networks are being used, a VIP should be provided for each
      network, separated by spaces.
  vip_iface:
    type: string
    default: "eth0"
    description: |
      Default network interface to use for HA vip when it cannot be
      automatically determined.
  ad-user:
    type: string
    default: "wsgate"
    description: |
      Username to request from AD
  ad-groups:
    type: string
    default: "Users"
    description: |
      Comma delimited list of active directory groups to request access to

